refactor: simplify post installation script

diff --git a/src/os-installation-config b/src/os-installation-config
--- a/src/os-installation-config
+++ b/src/os-installation-config
@@ -32,49 +32,32 @@ mirrors='
   https://mirror.yandex.ru/archlinux/$repo/os/$arch
 '
 
+path_to_copy="./post-installation-utilities.sh"
+
 post_bash_script='\
-su vlad -c bash <<EOF
 set -e
 
-intstall-deploy-configs() {
-  # Changes work directory
-  TEMP_DIRECTORY="$(mktemp -d)"
-  cd "$TEMP_DIRECTORY"
+# Mandatory variables
+DEPLOY_CONFIGS_INSTANCE="INSTANCE_HERE"
+USER_PASSWORD_FOR_SUDO="PASSWORD_HERE"
 
-  # Gets binary urs
-  curl -o ./deploy-configs-release.json \
-    https://api.github.com/repos/backdround/deploy-configs/releases/latest
-  echo ".assets[] \
-    | select(.name | match(\"deploy-configs-linux-amd64-.*[.]tar[.]gz\")) \
-    | .browser_download_url" \
-      > ./query.jq
-  BINARY_URL="$(jq -r -f ./query.jq ./deploy-configs-release.json)"
+mv /root/post-installation-utilities.sh /tmp
 
-  # Gets binary
-  curl -L -o ./deploy-configs.tar.gz "$BINARY_URL"
-  tar -xvf ./deploy-configs.tar.gz
-
-  # Deploy binary
-  mkdir -p ~/go/bin/
-  mv -f ./deploy-configs ~/go/bin/
-
-  # Cleans up
-  cd - > /dev/null
-  rm -rf "$TEMP_DIRECTORY"
-}
-
-intstall-deploy-configs
+su vlad -c bash <<EOF
+set -e
+source /tmp/post-installation-utilities.sh
 
 # Clones configuration
 git clone https://github.com/backdround/configuration.git ~/configuration
 cd ~/configuration
 
 # Deploys configs
-~/go/bin/deploy-configs INSTANCE_HERE || {
-  echo "Error occurs while deploying configs"
+download-deploy-configs ~/go/bin/
+~/go/bin/deploy-configs "$DEPLOY_CONFIGS_INSTANCE" || {
+  error "Error occurs while deploying configs" || true
 }
 
 # Configurates system
-./init.sh POSSIBLE_PASSWORD_HERE
+./init.sh "$USER_PASSWORD_FOR_SUDO"
 EOF
 '
